### ISSUE TITLE
View all friends' activity

### ISSUE THREAD

**Issue by matthew-thor** [boripama/capstone#1]
As a user, I want to see all my friends' activities when I log in so that I can interact with and encourage them

**Comment by matthew-thor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User database model](https://trello.com/c/TeHHfgub/1-user-database-model)

**Comment by matthew-thor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Run data database model](https://trello.com/c/rRonv8Ig/2-run-data-database-model)

**Comment by matthew-thor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["All activities" React component](https://trello.com/c/TWRGRQtN/3-all-activities-react-component)

**Comment by matthew-thor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Activities reducer](https://trello.com/c/7aiufa49/4-activities-reducer)

**Comment by matthew-thor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Activities API route(s)](https://trello.com/c/tCFjam0m/5-activities-api-routes)

**Comment by armyofbear136** [comment]
nearby upcoming events??

**Comment by PatrickGund** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["All activities" React component](https://trello.com/c/TWRGRQtN/3-all-activities-react-component)
