### ISSUE TITLE
Display next 10 activities

### ISSUE THREAD

**Issue by matthew-thor** [boripama/capstone#105]
As a user, I want to be able to click a button to see the next 10 activities (whether they're my own or my friends') so that I can view more than 10 total activities

**Comment by PatrickGund** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [display next 10 activities](https://trello.com/c/Y9QxBSvx/84-display-next-10-activities)

**Comment by PatrickGund** [comment]
complete
