### ISSUE TITLE
user's profile

### ISSUE THREAD

**Issue by armyofbear136** [boripama/capstone#108]
as a user I want to be able to navigate to a specific user's profile or my own

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [user profile page (using all activities component)](https://trello.com/c/xJD39Bbi/79-user-profile-page-using-all-activities-component)

**Comment by matthew-thor** [comment]
see #86

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [make total followers update in a more concrete way](https://trello.com/c/MouBnGHd/96-make-total-followers-update-in-a-more-concrete-way)

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix totalFollowers](https://trello.com/c/JUwcoJ1V/95-fix-totalfollowers)
