### ISSUE TITLE
friendship suggestions view

### ISSUE THREAD

**Issue by armyofbear136** [boripama/capstone#14]
as a user i want to be able to have ananda suggest friends for me based on similar activity

**Comment by matthew-thor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Basic friend recommendation engine](https://trello.com/c/eim58aq6/25-basic-friend-recommendation-engine)

**Comment by matthew-thor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Basic comparison for "center" points of activities](https://trello.com/c/PHdmbT1C/31-basic-comparison-for-center-points-of-activities)
