### ISSUE TITLE
view a single activity

### ISSUE THREAD

**Issue by armyofbear136** [boripama/capstone#3]
As a user I want to be able to view as many details about a specific activity as possilbe

**Comment by matthew-thor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [single activity view](https://trello.com/c/oyP4sN56/9-single-activity-view)

**Comment by matthew-thor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [testing activity reducer and component](https://trello.com/c/BYx7Y1rR/17-testing-activity-reducer-and-component)

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [creating front end route for single activity page](https://trello.com/c/xUP0AtAo/18-creating-front-end-route-for-single-activity-page)

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [gettin polylines rendered on map components](https://trello.com/c/DZyRl6GT/29-gettin-polylines-rendered-on-map-components)
