### ISSUE TITLE
Follower approve/deny feature

### ISSUE THREAD

**Issue by matthew-thor** [boripama/capstone#50]
As a user, I want to be able to approve or deny a follower request so that I can better protect my privacy

**Comment by PatrickGund** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [connect friend request button from front end to backend.](https://trello.com/c/xfJzptY2/48-connect-friend-request-button-from-front-end-to-backend)

**Comment by matthew-thor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update follower count on user profile card](https://trello.com/c/njSPUfh7/66-update-follower-count-on-user-profile-card)

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add ability to approve and reject followers](https://trello.com/c/U5drix2i/78-add-ability-to-approve-and-reject-followers)

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [follow and unfollow from userprofile](https://trello.com/c/UtCB3hxG/83-follow-and-unfollow-from-userprofile)

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [remove followers from your profile](https://trello.com/c/J2y8dfVj/86-remove-followers-from-your-profile)
