### ISSUE TITLE
Comments on activities

### ISSUE THREAD

**Issue by matthew-thor** [boripama/capstone#55]
As a user, I want to be able to leave a comment on my friends' activities so that I can interact with and encourage them

**Comment by matthew-thor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Set up comments in database](https://trello.com/c/jYlEZMmk/35-set-up-comments-in-database)

**Comment by matthew-thor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Comments API routes](https://trello.com/c/osKGRNep/49-comments-api-routes)

**Comment by bonddavis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adding/submitting comments to Comments component](https://trello.com/c/Vh4WLnna/46-adding-submitting-comments-to-comments-component)

**Comment by matthew-thor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Render comments on an activity](https://trello.com/c/Ua8k7WuS/61-render-comments-on-an-activity)

**Comment by matthew-thor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Complete Comments features](https://trello.com/c/XJ4I5StT/67-complete-comments-features)
