### ISSUE TITLE
building database/seed

### ISSUE THREAD

**Issue by armyofbear136** [boripama/capstone#6]
as a developer i want to have a seed file and working database connections

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [seed generation](https://trello.com/c/Fl0THiwL/10-seed-generation)

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [database definition](https://trello.com/c/VGMt4ZXW/11-database-definition)

**Comment by matthew-thor** [comment]
basic seed and db models are done and merged
