### ISSUE TITLE
Display list of users own activities

### ISSUE THREAD

**Issue by bonddavis** [boripama/capstone#71]
As a user, I should be able to view a list of all of my activities on my home page.

**Comment by bonddavis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User home page](https://trello.com/c/RiSLVKAQ/50-user-home-page)

**Comment by matthew-thor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Show own activities only](https://trello.com/c/AeLjYmJl/62-show-own-activities-only)

**Comment by PatrickGund** [comment]
complete
