### ISSUE TITLE
Input/update user zip code

### ISSUE THREAD

**Issue by matthew-thor** [boripama/capstone#83]
As a user, I want to be able to input my zip code and update it later so that I can receive better friend recommendations

**Comment by matthew-thor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User zipcode input/update](https://trello.com/c/yJezH62m/63-user-zipcode-input-update)

**Comment by PatrickGund** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User zipcode input/update](https://trello.com/c/yJezH62m/63-user-zipcode-input-update)

**Comment by matthew-thor** [comment]
merged
