### ISSUE TITLE
Own user/other user views

### ISSUE THREAD

**Issue by matthew-thor** [boripama/capstone#86]
As a user, I want to see update fields when I access my own page and activity info when I access another user's page so that I can both edit my own info and see the activities of others

**Comment by matthew-thor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Redirect to Activity page for a User when you want to view their profile.](https://trello.com/c/xvPmj5js/57-redirect-to-activity-page-for-a-user-when-you-want-to-view-their-profile)

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [spruce up ProfileDescription component](https://trello.com/c/lPfcQEVq/82-spruce-up-profiledescription-component)

**Comment by PatrickGund** [comment]
complete
