### ISSUE TITLE
View list of followers

### ISSUE THREAD

**Issue by matthew-thor** [boripama/capstone#88]
As a user, I want to be able to view a list of all my followers so that I can manage those relationships and see their profiles more easily

**Comment by matthew-thor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [View a list of all of my followers/friends so I can redirect to their activity pages](https://trello.com/c/CshEx2F4/69-view-a-list-of-all-of-my-followers-friends-so-i-can-redirect-to-their-activity-pages)

**Comment by PatrickGund** [comment]
completed.
